### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by bluelemonade** [Tostapunk/PC-Control-telegram-bot#1]
Hi,

I am interested to test the bot. I got following error:

Traceback (most recent call last):
  File "E:\_python\PC-Control-telegram-bot-master\bot.py", line 5, in <module>
    from telegram.ext import Updater, CommandHandler
  File "C:\Python34\lib\site-packages\telegram\ext\__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError'

regards

**Comment by Tostapunk** [comment]
It should be fixed now, maybe you'll need to delete the telegram module from your python folder
