### ISSUE TITLE
PIL Import Error

### ISSUE THREAD

**Issue by advokatb** [Tostapunk/PC-Control-telegram-bot#2]
Hi. Thanks for this bot. 
Please help with this:
```
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    import pyscreenshot as ImageGrab
  File "D:\Program\Python\Python27\lib\site-packages\pyscreenshot\__init__.py", line 1, in <module>
    from PIL import Image
ImportError: No module named PIL
```
How can it be fixed?

**Comment by advokatb** [comment]
`pip install Pillow` solved the problem
